//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _8_11_Messenger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int ID { get; set; }
        public string userid { get; set; }
        public string roomid { get; set; }
        public string dialog { get; set; }
        public string chatTime { get; set; }
        public Nullable<bool> seen { get; set; }
        public Nullable<int> dialogid { get; set; }
    }
}
